{{- if .Values.metabase.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qr-app.fullname" . }}-metabase
  labels:
    {{- include "qr-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metabase.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qr-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: metabase
---
{{- end }}
