apiVersion: v1
kind: Service
metadata:
  name: {{ include "qr-app.fullname" . }}-backend
  labels:
    {{- include "qr-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.backend.port | default 8000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qr-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qr-app.fullname" . }}-frontend
  labels:
    {{- include "qr-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.frontend.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qr-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
