apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
<span style="--i: 2; --x: 0; --y: 1"><a href="/admin/orders" title="Ordini"><ion-icon name="receipt-outline"></ion-icon></a></span>

          <span style="--i: 