# app-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-cert
  namespace: qr
spec:
  secretName: web-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - orders.local
