# metabase-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metabase-cert
  namespace: qr
spec:
  secretName: metabase-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - metabase.local
  ipAddresses:
    - "172.21.30.223"